import type {
  CampaignState,
  CompetitorState,
  DepartmentDefinition,
  DepartmentId,
  GameState,
  ProductBlueprint,
  TechDefinition,
} from "./types";
import {
  createStarterResearchLevels,
  createStarterConfiguration,
  evaluatePcBuild,
  STARTER_PART_IDS,
} from "./pc-system";

export const GAME_VERSION = 25;
export const STORAGE_KEY = "circuit-tycoon-save-v1";
export const GAME_START_YEAR = 1984;
export const DAYS_PER_MONTH = 30;
export const DAYS_PER_YEAR = 360;

export const DEPARTMENTS: Record<DepartmentId, DepartmentDefinition> = {
  production: {
    id: "production",
    name: "Produktion",
    shortName: "Fertigung",
    description: "Baut Produkte, reduziert Ausschuss und hält Lieferzeiten kurz.",
    salaryPerDay: 112,
    color: "#28d7b0",
  },
  research: {
    id: "research",
    name: "Forschung & Entwicklung",
    shortName: "Forschung",
    description: "Erzeugt Forschungspunkte und erschließt neue Technologiewellen.",
    salaryPerDay: 184,
    color: "#8b7cff",
  },
  marketing: {
    id: "marketing",
    name: "Marketing",
    shortName: "Marketing",
    description: "Stärkt Marke und Nachfrage, besonders bei neuen Produkten.",
    salaryPerDay: 148,
    color: "#ff9f5a",
  },
  sales: {
    id: "sales",
    name: "Vertrieb",
    shortName: "Vertrieb",
    description: "Wandelt Nachfrage in Verkäufe und bessere Händlerkonditionen um.",
    salaryPerDay: 139,
    color: "#58a6ff",
  },
  finance: {
    id: "finance",
    name: "Finanzen & Recht",
    shortName: "Finanzen",
    description: "Senkt Finanzierungskosten und schützt die Unternehmensführung.",
    salaryPerDay: 196,
    color: "#f1c75b",
  },
};

export const TECH_TREE: TechDefinition[] = [
  {
    id: "micro8",
    name: "8-Bit-Mikroarchitektur",
    category: "hardware",
    description: "Die Grundlage für kompakte, bezahlbare Heimcomputer.",
    cost: 0,
    prerequisites: [],
    era: 0,
    icon: "cpu",
    effects: ["Schaltet den Circuit One frei"],
  },
  {
    id: "silicon16",
    name: "16-Bit-Silizium",
    category: "hardware",
    description: "Mehr Adressraum, schnellere Anwendungen und bessere Grafik.",
    cost: 320,
    prerequisites: ["micro8"],
    era: 1,
    icon: "cpu",
    effects: ["Neue Computerklasse", "+6 % Produktqualität"],
  },
  {
    id: "robotic-assembly",
    name: "Robotische Montage",
    category: "manufacturing",
    description: "Standardisierte Fertigung senkt Fehlerquote und Stückkosten.",
    cost: 420,
    prerequisites: ["micro8"],
    era: 1,
    icon: "production",
    effects: ["Automatisierung Stufe 2", "−8 % Stückkosten"],
  },
  {
    id: "graphical-os",
    name: "Grafische Oberfläche",
    category: "software",
    description: "Fenster, Maus und Icons machen Computer massentauglich.",
    cost: 680,
    prerequisites: ["silicon16"],
    era: 2,
    icon: "monitor",
    effects: ["Schaltet Vision Desktop frei", "+5 Marke"],
  },
  {
    id: "network-stack",
    name: "Netzwerkprotokolle",
    category: "network",
    description: "Verbindet Arbeitsplätze und öffnet den Geschäftskundenmarkt.",
    cost: 760,
    prerequisites: ["silicon16"],
    era: 2,
    icon: "cloud",
    effects: ["Schaltet NetCore Server frei", "+8 % B2B-Nachfrage"],
  },
  {
    id: "portable-computing",
    name: "Portable Computing",
    category: "hardware",
    description: "Energieeffiziente Boards und kompakte Displays für unterwegs.",
    cost: 860,
    prerequisites: ["silicon16"],
    era: 2,
    icon: "monitor",
    effects: ["Schaltet Atlas Notebook frei"],
  },
  {
    id: "lithium-cells",
    name: "Lithium-Energiespeicher",
    category: "hardware",
    description: "Hohe Energiedichte ohne das Gewicht alter Akkutechnik.",
    cost: 1_150,
    prerequisites: ["portable-computing"],
    era: 3,
    icon: "bolt",
    effects: ["Mobile Produkte", "+10 % Gerätequalität"],
  },
  {
    id: "cellular-radio",
    name: "Digitale Mobilfunktechnik",
    category: "network",
    description: "Sprach- und Datendienste über effiziente Funkmodule.",
    cost: 1_380,
    prerequisites: ["network-stack", "lithium-cells"],
    era: 3,
    icon: "phone",
    effects: ["Schaltet Relay Phone frei"],
  },
  {
    id: "lean-fabs",
    name: "Lean-Fertigung",
    category: "manufacturing",
    description: "Just-in-time Lieferketten und statistische Qualitätskontrolle.",
    cost: 1_240,
    prerequisites: ["robotic-assembly"],
    era: 3,
    icon: "production",
    effects: ["−12 % Stückkosten", "+15 % Kapazität"],
  },
  {
    id: "touch-interface",
    name: "Multi-Touch-Interface",
    category: "hardware",
    description: "Kapazitive Displays verschmelzen Bedienung und Anzeige.",
    cost: 1_720,
    prerequisites: ["cellular-radio", "graphical-os"],
    era: 4,
    icon: "phone",
    effects: ["Schaltet Pulse Smartphone frei", "+8 Marke"],
  },
  {
    id: "cloud-platform",
    name: "Cloud-Plattform",
    category: "network",
    description: "Skalierbare Rechenzentren verwandeln Hardware in Services.",
    cost: 2_150,
    prerequisites: ["network-stack", "graphical-os"],
    era: 4,
    icon: "cloud",
    effects: ["Schaltet Orbit Cloud frei", "Wiederkehrende Umsätze"],
  },
  {
    id: "nanometer-chips",
    name: "Nanometer-Fertigung",
    category: "hardware",
    description: "Dichtere Schaltkreise liefern mehr Leistung pro Watt.",
    cost: 2_480,
    prerequisites: ["lean-fabs", "lithium-cells"],
    era: 4,
    icon: "cpu",
    effects: ["Schaltet Vector SoC frei", "−10 % Energiekosten"],
  },
  {
    id: "machine-learning",
    name: "Maschinelles Lernen",
    category: "software",
    description: "Datengetriebene Modelle verbessern Produkte und Prognosen.",
    cost: 3_150,
    prerequisites: ["cloud-platform", "nanometer-chips"],
    era: 5,
    icon: "sparkles",
    effects: ["Schaltet Synapse AI frei", "+15 % Nachfrageprognose"],
  },
  {
    id: "edge-ai",
    name: "Edge-AI-Chips",
    category: "hardware",
    description: "Spezialisierte Beschleuniger bringen KI direkt ins Gerät.",
    cost: 4_300,
    prerequisites: ["machine-learning", "touch-interface"],
    era: 6,
    icon: "cpu",
    effects: ["Schaltet Halo Device frei", "+18 % Marge"],
  },
];

export const PRODUCT_BLUEPRINTS: ProductBlueprint[] = [
  {
    id: "circuit-one",
    name: "Circuit One",
    category: "computer",
    tagline: "Computer für alle.",
    description: "Ein schlichter 8-Bit-Heimcomputer mit Tastatur und Kassettenlaufwerk.",
    era: 0,
    requiredTech: ["micro8"],
    developmentCost: 0,
    basePrice: 1_299,
    unitCost: 760,
    baseDemand: 15,
    quality: 30,
    icon: "computer",
    accent: "#44d7c5",
  },
  {
    id: "vertex-16",
    name: "Vertex 16",
    category: "computer",
    tagline: "Mehr Leistung. Weniger Warten.",
    description: "Ein leistungsfähiger 16-Bit-Rechner für Zuhause und kleine Büros.",
    era: 1,
    requiredTech: ["silicon16"],
    developmentCost: 78_000,
    basePrice: 1_899,
    unitCost: 890,
    baseDemand: 25,
    quality: 45,
    icon: "computer",
    accent: "#6ea8ff",
  },
  {
    id: "vision-desktop",
    name: "Vision Desktop",
    category: "computer",
    tagline: "Arbeit wird sichtbar.",
    description: "Maus, Grafikoberfläche und ein gestochen scharfes Farbdisplay.",
    era: 2,
    requiredTech: ["graphical-os"],
    developmentCost: 210_000,
    basePrice: 2_499,
    unitCost: 1_080,
    baseDemand: 39,
    quality: 61,
    icon: "computer",
    accent: "#9a8cff",
  },
  {
    id: "atlas-notebook",
    name: "Atlas Notebook",
    category: "computer",
    tagline: "Dein Büro reist mit.",
    description: "Mobiles Arbeiten mit integriertem Display und kompakter Bauform.",
    era: 2,
    requiredTech: ["portable-computing"],
    developmentCost: 265_000,
    basePrice: 3_199,
    unitCost: 1_420,
    baseDemand: 33,
    quality: 58,
    icon: "computer",
    accent: "#f3b75d",
  },
  {
    id: "netcore-server",
    name: "NetCore Server",
    category: "components",
    tagline: "Das Rückgrat des Büros.",
    description: "Zuverlässige Netzwerkhardware für wachsende Unternehmen.",
    era: 2,
    requiredTech: ["network-stack"],
    developmentCost: 235_000,
    basePrice: 5_900,
    unitCost: 2_730,
    baseDemand: 13,
    quality: 64,
    icon: "components",
    accent: "#52b8ff",
  },
  {
    id: "relay-phone",
    name: "Relay Phone",
    category: "phone",
    tagline: "Erreichbar, wo immer du bist.",
    description: "Ein robustes digitales Mobiltelefon mit starker Akkulaufzeit.",
    era: 3,
    requiredTech: ["cellular-radio"],
    developmentCost: 440_000,
    basePrice: 899,
    unitCost: 390,
    baseDemand: 62,
    quality: 63,
    icon: "phone",
    accent: "#ff9f65",
  },
  {
    id: "pulse-smartphone",
    name: "Pulse Smartphone",
    category: "phone",
    tagline: "Die Welt in deiner Hand.",
    description: "Touchscreen, Browser und Medienplayer in einem einzigen Gerät.",
    era: 4,
    requiredTech: ["touch-interface"],
    developmentCost: 980_000,
    basePrice: 749,
    unitCost: 285,
    baseDemand: 138,
    quality: 78,
    icon: "phone",
    accent: "#ff6f91",
  },
  {
    id: "orbit-cloud",
    name: "Orbit Cloud",
    category: "software",
    tagline: "Rechenleistung ohne Grenzen.",
    description: "Ein skalierbarer Cloud-Dienst mit planbaren Abo-Erlösen.",
    era: 4,
    requiredTech: ["cloud-platform"],
    developmentCost: 1_250_000,
    basePrice: 349,
    unitCost: 58,
    baseDemand: 190,
    quality: 79,
    icon: "software",
    accent: "#4bd6ff",
  },
  {
    id: "vector-soc",
    name: "Vector SoC",
    category: "components",
    tagline: "Mehr Leistung pro Watt.",
    description: "Ein integrierter Hochleistungschip für Partner und eigene Geräte.",
    era: 4,
    requiredTech: ["nanometer-chips"],
    developmentCost: 1_100_000,
    basePrice: 189,
    unitCost: 61,
    baseDemand: 245,
    quality: 82,
    icon: "components",
    accent: "#9cec6a",
  },
  {
    id: "synapse-ai",
    name: "Synapse AI",
    category: "software",
    tagline: "Entscheidungen mit Vorsprung.",
    description: "KI-Software für Prognosen, Automatisierung und kreative Arbeit.",
    era: 5,
    requiredTech: ["machine-learning"],
    developmentCost: 2_400_000,
    basePrice: 599,
    unitCost: 74,
    baseDemand: 290,
    quality: 88,
    icon: "software",
    accent: "#c68cff",
  },
  {
    id: "halo-device",
    name: "Halo Device",
    category: "phone",
    tagline: "Intelligenz, die bei dir bleibt.",
    description: "Ein KI-Gerät mit lokaler Verarbeitung und adaptiver Oberfläche.",
    era: 6,
    requiredTech: ["edge-ai"],
    developmentCost: 4_800_000,
    basePrice: 1_199,
    unitCost: 335,
    baseDemand: 360,
    quality: 94,
    icon: "phone",
    accent: "#63f0ce",
  },
];

export const CAMPAIGNS: Array<CampaignState & { upfrontCost: number; description: string }> = [
  {
    id: "trade-show",
    name: "Technikmesse",
    description: "Live-Demos überzeugen Fachpresse und Händler.",
    daysRemaining: 45,
    totalDays: 45,
    dailyCost: 1_100,
    upfrontCost: 18_000,
    demandBoost: 0.15,
    brandBoost: 0.08,
  },
  {
    id: "prime-time",
    name: "TV-Offensive",
    description: "Breite Reichweite für einen schnellen Markendurchbruch.",
    daysRemaining: 60,
    totalDays: 60,
    dailyCost: 3_800,
    upfrontCost: 65_000,
    demandBoost: 0.34,
    brandBoost: 0.17,
  },
  {
    id: "community",
    name: "Developer Community",
    description: "Events und Werkzeuge binden Fans langfristig an die Plattform.",
    daysRemaining: 90,
    totalDays: 90,
    dailyCost: 2_100,
    upfrontCost: 42_000,
    demandBoost: 0.2,
    brandBoost: 0.25,
  },
];

type CompetitorTemplate = Omit<
  CompetitorState,
  "averageCost" | "realizedProfit" | "priceHistory"
>;

const GENERATED_COMPETITOR_PROFILES: Array<{
  sector: string;
  description: string;
  segment?: CompetitorState["pcSegment"];
  pricePosition?: number;
}> = [
  { sector: "PC-Discounter", description: "Konzentriert sich auf preiswerte Rechner und hohe Stückzahlen.", segment: "budget", pricePosition: 0.78 },
  { sector: "Business-PCs", description: "Beliefert Büros, Bildungseinrichtungen und öffentliche Auftraggeber.", segment: "budget", pricePosition: 0.96 },
  { sector: "Consumer-PCs", description: "Verkauft ausgewogene Computer über Handel und Direktvertrieb.", segment: "mainstream", pricePosition: 1 },
  { sector: "Kreativ-PCs", description: "Entwickelt leistungsfähige Systeme für Medien- und Kreativarbeit.", segment: "mainstream", pricePosition: 1.09 },
  { sector: "Gaming-PCs", description: "Tritt mit schnellen Produktzyklen im Enthusiastenmarkt an.", segment: "performance", pricePosition: 1.14 },
  { sector: "Workstations", description: "Baut hochpreisige Systeme für Forschung und professionelle Anwendungen.", segment: "performance", pricePosition: 1.28 },
  { sector: "Halbleiter", description: "Entwickelt spezialisierte Chips für Computer und Rechenzentren." },
  { sector: "Datenspeicher", description: "Produziert Speichertechnik für PCs, Server und Unternehmenssysteme." },
  { sector: "Netzwerktechnik", description: "Liefert Netzwerkkomponenten und Infrastruktur für Geschäftskunden." },
  { sector: "Cloud & Software", description: "Erwirtschaftet wiederkehrende Erlöse mit Software und Cloud-Diensten." },
  { sector: "Industrieautomation", description: "Automatisiert Fertigungslinien und elektronische Montageprozesse." },
  { sector: "Energie & Kühlung", description: "Entwickelt Netzteile, Kühlsysteme und effiziente Elektronik." },
];

const GENERATED_COMPETITOR_PREFIXES = [
  "Aurora", "Atlas", "BluePeak", "CoreAxis", "Delta", "Eon", "Flux",
  "Granite", "Horizon", "Ion", "Keystone", "NovaCircuit", "Optima",
  "Parallax", "Quanta", "Silverline", "Titan", "Vector", "Zenith",
];

const GENERATED_COMPETITOR_SUFFIXES = [
  "Technologies", "Digital", "Microsystems", "Computing",
];

const GENERATED_COMPETITOR_COLORS = [
  "#2563EB", "#0891B2", "#0F766E", "#16A34A", "#65A30D", "#CA8A04",
  "#EA580C", "#DC2626", "#DB2777", "#9333EA", "#7C3AED", "#475569",
];

function stableCompetitorValue(index: number, salt: number) {
  const raw = Math.sin((index + 1) * 12.9898 + salt * 78.233) * 43_758.5453;
  return raw - Math.floor(raw);
}

function createGeneratedCompetitors(count: number): CompetitorTemplate[] {
  return Array.from({ length: Math.max(0, count) }, (_, index) => {
    const profile = GENERATED_COMPETITOR_PROFILES[index % GENERATED_COMPETITOR_PROFILES.length];
    const prefix = GENERATED_COMPETITOR_PREFIXES[index % GENERATED_COMPETITOR_PREFIXES.length];
    const suffix = GENERATED_COMPETITOR_SUFFIXES[Math.floor(index / GENERATED_COMPETITOR_PREFIXES.length)];
    const scale = index % 8;
    const revenue = Math.round(
      2_400_000 * 1.82 ** scale * (0.78 + stableCompetitorValue(index, 1) * 0.5),
    );
    const innovation = Math.round(30 + stableCompetitorValue(index, 2) * 64);
    const brand = Math.round(18 + stableCompetitorValue(index, 3) * 67);
    const growth = -0.045 + stableCompetitorValue(index, 4) * 0.275;
    const debtRatio = 0.1 + stableCompetitorValue(index, 5) * 0.64;
    const profitMargin = -0.015 + stableCompetitorValue(index, 6) * 0.225;
    const financialHealth = Math.round(
      Math.max(24, Math.min(98, 88 + profitMargin * 42 + growth * 18 - debtRatio * 58)),
    );
    const sentiment = Math.round(
      Math.max(20, Math.min(88, 48 + growth * 75 + profitMargin * 35 - debtRatio * 18)),
    );
    const sharesOutstanding = Math.round(
      (900_000 + scale * 620_000) * (0.85 + stableCompetitorValue(index, 7) * 0.35),
    );
    const valuationMultiple = Math.max(
      0.28,
      Math.min(1.45, 0.42 + profitMargin * 1.8 + growth * 0.75 + innovation / 750),
    );
    const fairValue = Math.max(0.2, revenue * valuationMultiple / sharesOutstanding);
    const price = Math.max(
      0.2,
      fairValue * (0.91 + stableCompetitorValue(index, 8) * 0.18),
    );
    const marketShare = 0.4 + stableCompetitorValue(index, 9) * (1.4 + scale * 0.62);
    const history = Array.from({ length: 5 }, (_, historyIndex) => {
      if (historyIndex === 4) return price;
      const trend = 0.87 + historyIndex * 0.032;
      const variation = (stableCompetitorValue(index, 20 + historyIndex) - 0.5) * 0.06;
      return Math.max(0.2, price * (trend + variation));
    });
    const acquisitionPerk = profile.segment === "budget"
      ? "+0,5 Prozentpunkte Marktanteil durch Volumenvertrieb"
      : profile.segment === "mainstream"
        ? "+2 Marke durch zusätzliche Handelsreichweite"
        : profile.segment === "performance"
          ? "+250 Forschungspunkte aus dem Entwicklungsteam"
          : "+2 Reputation durch zusätzliche Technologiekompetenz";

    return {
      id: `market-company-${String(index + 1).padStart(3, "0")}`,
      name: `${prefix} ${suffix}`,
      ticker: `N${(index + 24).toString(36).toUpperCase().padStart(2, "0")}`,
      sector: profile.sector,
      color: GENERATED_COMPETITOR_COLORS[index % GENERATED_COMPETITOR_COLORS.length],
      description: profile.description,
      sharesOutstanding,
      price,
      fairValue,
      revenue,
      profitMargin,
      growth,
      innovation,
      brand,
      debtRatio,
      marketShare,
      sentiment,
      history,
      status: "active",
      ownedShares: 0,
      lastReason: financialHealth < 45
        ? "Schwache Bilanz und hoher Wettbewerbsdruck erhöhen das Insolvenzrisiko."
        : growth > 0.14
          ? "Produktnachfrage und Investitionen treiben das operative Wachstum."
          : "Umsatz, Marge und Bewertung entwickeln sich im Rahmen des Marktsegments.",
      acquisitionPerk,
      financialHealth,
      pcSegment: profile.segment,
      pcPricePosition: profile.pricePosition
        ? profile.pricePosition * (0.94 + stableCompetitorValue(index, 10) * 0.12)
        : undefined,
    };
  });
}

function createCompetitors(): CompetitorState[] {
  const competitors: CompetitorTemplate[] = [
    {
      id: "microfab",
      name: "MicroFab Assembly",
      ticker: "MFB",
      sector: "Auftragsfertigung",
      color: "#F2B84B",
      description: "Kleiner Leiterplatten- und Gehäusefertiger mit knappen Margen, aber verlässlichen Industriekunden.",
      sharesOutstanding: 1_000_000,
      price: 0.52,
      fairValue: 0.56,
      revenue: 1_000_000,
      profitMargin: 0.055,
      growth: 0.075,
      innovation: 32,
      brand: 18,
      debtRatio: 0.34,
      marketShare: 0.65,
      sentiment: 48,
      history: [0.46, 0.47, 0.48, 0.5, 0.52],
      status: "active",
      ownedShares: 0,
      lastReason: "Neue Fertigungsaufträge gleichen die geringe Marge aus.",
      acquisitionPerk: "−2 % PC-Stückkosten und +1 Fabrikstufe",
    },
    {
      id: "coolwave",
      name: "CoolWave Systems",
      ticker: "CLW",
      sector: "Energie & Kühlung",
      color: "#2DD4BF",
      description: "Spezialist für Netzteile und Kühllösungen mit solider Bilanz und wachsendem OEM-Geschäft.",
      sharesOutstanding: 1_200_000,
      price: 1.98,
      fairValue: 1.86,
      revenue: 3_100_000,
      profitMargin: 0.085,
      growth: 0.105,
      innovation: 55,
      brand: 27,
      debtRatio: 0.22,
      marketShare: 1.1,
      sentiment: 58,
      history: [1.62, 1.72, 1.82, 1.91, 1.98],
      status: "active",
      ownedShares: 0,
      lastReason: "OEM-Verträge treiben den Kurs leicht über den fundamentalen Wert.",
      acquisitionPerk: "+4 PC-Qualität und +1 Automatisierungsstufe",
    },
    {
      id: "datavault",
      name: "DataVault Storage",
      ticker: "DVT",
      sector: "Datenspeicher",
      color: "#60A5FA",
      description: "Entwickelt Festplattencontroller und frühe Flash-Speicher für PCs und Server.",
      sharesOutstanding: 1_800_000,
      price: 3.65,
      fairValue: 3.99,
      revenue: 9_200_000,
      profitMargin: 0.105,
      growth: 0.13,
      innovation: 61,
      brand: 35,
      debtRatio: 0.27,
      marketShare: 1.9,
      sentiment: 63,
      history: [3.22, 3.3, 3.42, 3.54, 3.65],
      status: "active",
      ownedShares: 0,
      lastReason: "Speichernachfrage wächst schneller als die aktuelle Bewertung.",
      acquisitionPerk: "−3 % PC-Stückkosten und +300 Forschungspunkte",
    },
    {
      id: "northbridge",
      name: "Northbridge Memory",
      ticker: "NBM",
      sector: "Arbeitsspeicher",
      color: "#A78BFA",
      description: "Forschungsstarker Speicherhersteller mit zyklischen Preisen und niedriger Verschuldung.",
      sharesOutstanding: 2_200_000,
      price: 7.45,
      fairValue: 7.23,
      revenue: 18_000_000,
      profitMargin: 0.13,
      growth: 0.155,
      innovation: 69,
      brand: 40,
      debtRatio: 0.19,
      marketShare: 3,
      sentiment: 67,
      history: [6.8, 6.95, 7.12, 7.3, 7.45],
      status: "active",
      ownedShares: 0,
      lastReason: "Hohe Speicherauslastung trifft auf einen bereits ambitionierten Kurs.",
      acquisitionPerk: "+10 % Forschungstempo und +350 Forschungspunkte",
    },
    {
      id: "orbitnet",
      name: "OrbitNet Infrastructure",
      ticker: "ORB",
      sector: "Netzwerkinfrastruktur",
      color: "#34D399",
      description: "Baut Unternehmensnetzwerke und Rechenzentren; hohe Investitionen belasten die Bilanz.",
      sharesOutstanding: 4_200_000,
      price: 15.6,
      fairValue: 14.37,
      revenue: 69_000_000,
      profitMargin: 0.145,
      growth: 0.16,
      innovation: 72,
      brand: 49,
      debtRatio: 0.41,
      marketShare: 4.7,
      sentiment: 55,
      history: [13.1, 13.6, 14.2, 14.9, 15.6],
      status: "active",
      ownedShares: 0,
      lastReason: "Netzwerkfantasie stützt den Kurs, die hohe Verschuldung begrenzt den fairen Wert.",
      acquisitionPerk: "+8 % Produktnachfrage und +6 Reputation",
    },
    {
      id: "luminagraphics",
      name: "Lumina Graphics",
      ticker: "LUX",
      sector: "Grafikprozessoren",
      color: "#F472B6",
      description: "Innovativer Grafikchip-Entwickler mit starkem Gaming- und Visualisierungswachstum.",
      sharesOutstanding: 5_500_000,
      price: 21.8,
      fairValue: 23.3,
      revenue: 126_000_000,
      profitMargin: 0.16,
      growth: 0.21,
      innovation: 88,
      brand: 60,
      debtRatio: 0.26,
      marketShare: 7,
      sentiment: 74,
      history: [17.6, 18.4, 19.5, 20.7, 21.8],
      status: "active",
      ownedShares: 0,
      lastReason: "Technologievorsprung und starkes Wachstum rechtfertigen ein hohes Multiple.",
      acquisitionPerk: "+8 PC-Qualität und +6 Marke",
    },
    {
      id: "helixrobotics",
      name: "Helix Robotics",
      ticker: "HLX",
      sector: "Industrieautomation",
      color: "#FB7185",
      description: "Profitabler Weltmarktführer für Fertigungsroboter und automatisierte Montagelinien.",
      sharesOutstanding: 8_800_000,
      price: 38.8,
      fairValue: 36.85,
      revenue: 310_000_000,
      profitMargin: 0.19,
      growth: 0.16,
      innovation: 82,
      brand: 68,
      debtRatio: 0.2,
      marketShare: 10.2,
      sentiment: 62,
      history: [36.4, 36.9, 37.6, 38.3, 38.8],
      status: "active",
      ownedShares: 0,
      lastReason: "Automatisierungsboom ist teilweise bereits im Kurs eingepreist.",
      acquisitionPerk: "+15 % Produktionskapazität und +1 Automatisierungsstufe",
    },
    {
      id: "monolith",
      name: "Monolith Systems",
      ticker: "MNL",
      sector: "Mainframes",
      color: "#70a9ff",
      description: "Dominant im Großkundengeschäft, profitabel, aber innovationsarm.",
      sharesOutstanding: 12_000_000,
      price: 42.4,
      fairValue: 43.1,
      revenue: 610_000_000,
      profitMargin: 0.16,
      growth: 0.035,
      innovation: 38,
      brand: 76,
      debtRatio: 0.18,
      marketShare: 24.8,
      pcSegment: "mainstream",
      pcPricePosition: 0.94,
      sentiment: 52,
      history: [39.8, 40.4, 41.1, 41.6, 42.4],
      status: "active",
      ownedShares: 0,
      lastReason: "Stabile Großkundenverträge stützen den fairen Wert.",
      acquisitionPerk: "+18 Marke und Zugang zu Großkunden",
    },
    {
      id: "pixelworks",
      name: "PixelWorks",
      ticker: "PXW",
      sector: "Personal Computer",
      color: "#c08cff",
      description: "Designstarke Computer mit loyaler Community und hohen Margen.",
      sharesOutstanding: 5_800_000,
      price: 28.7,
      fairValue: 30.2,
      revenue: 218_000_000,
      profitMargin: 0.12,
      growth: 0.12,
      innovation: 71,
      brand: 66,
      debtRatio: 0.24,
      marketShare: 12.4,
      pcSegment: "performance",
      pcPricePosition: 1.16,
      sentiment: 68,
      history: [23.9, 25.2, 26.1, 27.4, 28.7],
      status: "active",
      ownedShares: 0,
      lastReason: "Neue Produkte erhöhen Wachstum und Bewertungsmultiple.",
      acquisitionPerk: "+14 Produktqualität und +12 Marke",
    },
    {
      id: "telestar",
      name: "TeleStar Mobile",
      ticker: "TSM",
      sector: "Kommunikation",
      color: "#ff9d68",
      description: "Funkpionier mit teurem Netzaufbau und starkem Wachstum.",
      sharesOutstanding: 7_200_000,
      price: 17.9,
      fairValue: 18.3,
      revenue: 168_000_000,
      profitMargin: 0.075,
      growth: 0.18,
      innovation: 64,
      brand: 48,
      debtRatio: 0.52,
      marketShare: 8.7,
      sentiment: 61,
      history: [15.4, 15.9, 16.8, 17.2, 17.9],
      status: "active",
      ownedShares: 0,
      lastReason: "Wachstum überzeugt, hohe Schulden begrenzen den Kurs.",
      acquisitionPerk: "+12 Marktanteil im Mobilsegment",
    },
    {
      id: "nexabyte",
      name: "NexaByte Labs",
      ticker: "NBL",
      sector: "Halbleiter",
      color: "#79e08d",
      description: "Kleiner Chiphersteller mit exzellenter Forschung und volatilen Aufträgen.",
      sharesOutstanding: 3_100_000,
      price: 13.6,
      fairValue: 14.8,
      revenue: 61_000_000,
      profitMargin: 0.09,
      growth: 0.24,
      innovation: 84,
      brand: 31,
      debtRatio: 0.31,
      marketShare: 4.1,
      sentiment: 73,
      history: [10.1, 11.4, 12.2, 12.8, 13.6],
      status: "active",
      ownedShares: 0,
      lastReason: "Forschungsvorsprung hebt Wachstumserwartungen.",
      acquisitionPerk: "+700 Forschungspunkte und −6 % Stückkosten",
    },
    {
      id: "softunion",
      name: "SoftUnion",
      ticker: "SFU",
      sector: "Software",
      color: "#55d7db",
      description: "Betriebssysteme und Bürosoftware mit planbaren Lizenzerlösen.",
      sharesOutstanding: 8_400_000,
      price: 24.2,
      fairValue: 24.7,
      revenue: 245_000_000,
      profitMargin: 0.22,
      growth: 0.095,
      innovation: 59,
      brand: 58,
      debtRatio: 0.12,
      marketShare: 10.9,
      sentiment: 57,
      history: [22.8, 23.1, 23.5, 23.9, 24.2],
      status: "active",
      ownedShares: 0,
      lastReason: "Hohe Lizenzmarge sorgt für verlässlichen Cashflow.",
      acquisitionPerk: "+9 Marge bei Softwareprodukten",
    },
    {
      id: "ironclad",
      name: "Ironclad Computing",
      ticker: "IRC",
      sector: "Budget-PCs",
      color: "#64748B",
      description: "Großer Volumenanbieter für Schulen, Büros und preisbewusste Haushalte.",
      sharesOutstanding: 6_200_000,
      price: 8.4,
      fairValue: 8.1,
      revenue: 142_000_000,
      profitMargin: 0.055,
      growth: 0.08,
      innovation: 46,
      brand: 57,
      debtRatio: 0.43,
      marketShare: 8.2,
      sentiment: 51,
      history: [7.8, 8.0, 7.9, 8.2, 8.4],
      status: "active",
      ownedShares: 0,
      lastReason: "Hohe Stückzahlen gleichen die niedrigen Margen aus.",
      acquisitionPerk: "+12 % Absatzreichweite im Low-End-Segment",
      pcSegment: "budget",
      pcPricePosition: 0.82,
    },
    {
      id: "novahome",
      name: "NovaHome Electronics",
      ticker: "NHE",
      sector: "Consumer-PCs",
      color: "#0EA5E9",
      description: "Bekannte Handelsmarke mit günstigen Familien- und Einsteiger-PCs.",
      sharesOutstanding: 4_600_000,
      price: 11.2,
      fairValue: 11.8,
      revenue: 176_000_000,
      profitMargin: 0.072,
      growth: 0.11,
      innovation: 53,
      brand: 69,
      debtRatio: 0.31,
      marketShare: 9.1,
      sentiment: 59,
      history: [9.8, 10.1, 10.5, 10.9, 11.2],
      status: "active",
      ownedShares: 0,
      lastReason: "Breite Handelspräsenz sorgt für stetige Nachfrage.",
      acquisitionPerk: "+10 Marke und bessere Handelsabdeckung",
      pcSegment: "budget",
      pcPricePosition: 0.96,
    },
    {
      id: "vertex",
      name: "Vertex Personal Systems",
      ticker: "VPS",
      sector: "Mainstream-PCs",
      color: "#14B8A6",
      description: "Ausgewogene Rechner für Arbeit, Studium und Gelegenheitsspieler.",
      sharesOutstanding: 7_500_000,
      price: 19.6,
      fairValue: 20.1,
      revenue: 286_000_000,
      profitMargin: 0.105,
      growth: 0.14,
      innovation: 67,
      brand: 63,
      debtRatio: 0.25,
      marketShare: 11.6,
      sentiment: 64,
      history: [16.8, 17.6, 18.3, 19.0, 19.6],
      status: "active",
      ownedShares: 0,
      lastReason: "Ein starkes Preis-Leistungs-Verhältnis gewinnt Marktanteile.",
      acquisitionPerk: "+8 % Nachfrage im Massenmarkt",
      pcSegment: "mainstream",
      pcPricePosition: 1,
    },
    {
      id: "bytecraft",
      name: "ByteCraft Direct",
      ticker: "BCD",
      sector: "Direktvertrieb",
      color: "#8B5CF6",
      description: "Schlanker Direktanbieter, der PCs schnell an neue Technikgenerationen anpasst.",
      sharesOutstanding: 3_800_000,
      price: 14.1,
      fairValue: 14.9,
      revenue: 121_000_000,
      profitMargin: 0.088,
      growth: 0.19,
      innovation: 76,
      brand: 42,
      debtRatio: 0.37,
      marketShare: 5.8,
      sentiment: 66,
      history: [10.9, 11.7, 12.5, 13.4, 14.1],
      status: "active",
      ownedShares: 0,
      lastReason: "Schnelle Modellwechsel treiben Wachstum, erhöhen aber das Risiko.",
      acquisitionPerk: "+12 % Vertriebsproduktivität",
      pcSegment: "mainstream",
      pcPricePosition: 0.9,
      financialHealth: 76,
    },
    {
      id: "apex",
      name: "Apex Quantum PCs",
      ticker: "APQ",
      sector: "High-End-PCs",
      color: "#EC4899",
      description: "Technologieführer für Enthusiasten, Studios und wissenschaftliche Workstations.",
      sharesOutstanding: 5_100_000,
      price: 31.8,
      fairValue: 33.4,
      revenue: 204_000_000,
      profitMargin: 0.17,
      growth: 0.22,
      innovation: 91,
      brand: 58,
      debtRatio: 0.29,
      marketShare: 6.7,
      sentiment: 78,
      history: [24.2, 25.9, 27.8, 29.6, 31.8],
      status: "active",
      ownedShares: 0,
      lastReason: "Der aktuelle Leistungsvorsprung rechtfertigt hohe Preise.",
      acquisitionPerk: "+1 Stufe auf leistungsbezogene Forschung",
      pcSegment: "performance",
      pcPricePosition: 1.24,
    },
    {
      id: "officecore",
      name: "OfficeCore Industries",
      ticker: "OCI",
      sector: "Business-PCs",
      color: "#2563EB",
      description: "Großer Büroausstatter mit günstigen Flottenrechnern und langen Rahmenverträgen.",
      sharesOutstanding: 6_400_000,
      price: 12.8,
      fairValue: 13.1,
      revenue: 214_000_000,
      profitMargin: 0.082,
      growth: 0.095,
      innovation: 51,
      brand: 66,
      debtRatio: 0.28,
      marketShare: 8.4,
      sentiment: 57,
      history: [11.3, 11.7, 12.1, 12.5, 12.8],
      status: "active",
      ownedShares: 0,
      lastReason: "Mehrjährige Unternehmenskunden stabilisieren Umsatz und Marge.",
      acquisitionPerk: "+8 % Nachfrage bei Office-PCs",
      pcSegment: "budget",
      pcPricePosition: 0.98,
      financialHealth: 84,
    },
    {
      id: "meridian",
      name: "Meridian Computing",
      ticker: "MRC",
      sector: "Mainstream-PCs",
      color: "#16A34A",
      description: "Internationaler PC-Hersteller mit effizientem Handel und ausgewogenem Portfolio.",
      sharesOutstanding: 9_200_000,
      price: 22.4,
      fairValue: 23.2,
      revenue: 388_000_000,
      profitMargin: 0.118,
      growth: 0.135,
      innovation: 69,
      brand: 72,
      debtRatio: 0.24,
      marketShare: 12.8,
      sentiment: 67,
      history: [19.2, 20.1, 20.8, 21.6, 22.4],
      status: "active",
      ownedShares: 0,
      lastReason: "Skaleneffekte und ein breites Händlernetz stärken das Ergebnis.",
      acquisitionPerk: "+10 % internationale Vertriebsreichweite",
      pcSegment: "mainstream",
      pcPricePosition: 1.03,
      financialHealth: 91,
    },
    {
      id: "quantumgrid",
      name: "QuantumGrid Workstations",
      ticker: "QGW",
      sector: "Workstations",
      color: "#7C3AED",
      description: "Premiumanbieter für Forschung, Simulation und professionelle Medienproduktion.",
      sharesOutstanding: 4_900_000,
      price: 36.5,
      fairValue: 38.2,
      revenue: 238_000_000,
      profitMargin: 0.188,
      growth: 0.205,
      innovation: 94,
      brand: 61,
      debtRatio: 0.19,
      marketShare: 5.9,
      sentiment: 79,
      history: [29.8, 31.4, 33.2, 34.7, 36.5],
      status: "active",
      ownedShares: 0,
      lastReason: "Technologieführerschaft erlaubt hohe Preise, verlangt aber ständige Forschung.",
      acquisitionPerk: "+8 % High-End-Marge",
      pcSegment: "performance",
      pcPricePosition: 1.3,
      financialHealth: 94,
    },
    {
      id: "polarbyte",
      name: "PolarByte Systems",
      ticker: "PBS",
      sector: "Effiziente PCs",
      color: "#0891B2",
      description: "Wachsender Anbieter leiser, effizienter Rechner für Bildung und Kreativarbeit.",
      sharesOutstanding: 3_600_000,
      price: 9.7,
      fairValue: 10.4,
      revenue: 96_000_000,
      profitMargin: 0.094,
      growth: 0.175,
      innovation: 78,
      brand: 41,
      debtRatio: 0.33,
      marketShare: 4.6,
      sentiment: 65,
      history: [7.8, 8.2, 8.7, 9.2, 9.7],
      status: "active",
      ownedShares: 0,
      lastReason: "Energieeffizienz gewinnt Kunden, die Marke ist aber noch klein.",
      acquisitionPerk: "+1 Stufe Energieeffizienz-Forschung",
      pcSegment: "mainstream",
      pcPricePosition: 1.06,
      financialHealth: 79,
    },
    {
      id: "cedarlabs",
      name: "Cedar Labs Semiconductor",
      ticker: "CLS",
      sector: "Halbleiter",
      color: "#B45309",
      description: "Spezialisierter Chipentwickler mit zyklischen Großaufträgen und hoher F&E-Quote.",
      sharesOutstanding: 5_700_000,
      price: 17.3,
      fairValue: 18.1,
      revenue: 184_000_000,
      profitMargin: 0.142,
      growth: 0.16,
      innovation: 87,
      brand: 48,
      debtRatio: 0.26,
      marketShare: 4.2,
      sentiment: 70,
      history: [15.1, 15.8, 16.2, 16.9, 17.3],
      status: "active",
      ownedShares: 0,
      lastReason: "Neue Chipaufträge treiben Wachstum, Auftragspausen erhöhen das Kursrisiko.",
      acquisitionPerk: "+10 % CPU-Forschungstempo",
      financialHealth: 87,
    },
    {
      id: "redline",
      name: "Redline Performance",
      ticker: "RLP",
      sector: "Gaming-PCs",
      color: "#DC2626",
      description: "Aggressive Gaming-Marke mit hoher Leistung, knappen Margen und schnellen Modellwechseln.",
      sharesOutstanding: 4_200_000,
      price: 15.6,
      fairValue: 15.2,
      revenue: 152_000_000,
      profitMargin: 0.076,
      growth: 0.185,
      innovation: 83,
      brand: 55,
      debtRatio: 0.49,
      marketShare: 5.1,
      sentiment: 62,
      history: [13.8, 14.7, 14.3, 15.1, 15.6],
      status: "active",
      ownedShares: 0,
      lastReason: "Starke Produktstarts wechseln sich mit kostspieligen Modellübergängen ab.",
      acquisitionPerk: "+9 % Gaming-Nachfrage",
      pcSegment: "performance",
      pcPricePosition: 1.08,
      financialHealth: 68,
    },
    {
      id: "ember",
      name: "Ember Systems",
      ticker: "EMB",
      sector: "PC-Discounter",
      color: "#F97316",
      description: "Aggressiver Billiganbieter mit hoher Verschuldung und anfälliger Lieferkette.",
      sharesOutstanding: 2_900_000,
      price: 2.7,
      fairValue: 2.4,
      revenue: 38_000_000,
      profitMargin: 0.018,
      growth: -0.035,
      innovation: 35,
      brand: 26,
      debtRatio: 0.78,
      marketShare: 2.9,
      sentiment: 31,
      history: [4.1, 3.8, 3.4, 3.0, 2.7],
      status: "active",
      ownedShares: 0,
      lastReason: "Preiskampf und Schulden gefährden die Zahlungsfähigkeit.",
      acquisitionPerk: "+5 % Low-End-Marktanteil",
      pcSegment: "budget",
      pcPricePosition: 0.7,
      financialHealth: 38,
    },
  ];
  const completeMarket = [
    ...competitors,
    ...createGeneratedCompetitors(100 - competitors.length),
  ];
  return completeMarket.map((competitor) => ({
    ...competitor,
    averageCost: 0,
    realizedProfit: 0,
    financialHealth: competitor.financialHealth ?? 100,
    priceHistory: competitor.history.map((close, index, prices) => {
      const open = prices[index - 1] ?? close;
      return {
        day: index - prices.length + 1,
        open,
        high: Math.max(open, close),
        low: Math.min(open, close),
        close,
      };
    }),
  }));
}

export function createInitialState(now = Date.now()): GameState {
  const starterConfiguration = createStarterConfiguration();
  const starterBuild = evaluatePcBuild(starterConfiguration, "office");
  return {
    version: GAME_VERSION,
    companyName: "Circuit Forge",
    day: 0,
    speed: 1,
    previousSpeed: 1,
    difficulty: "realistic",
    cash: 225_000,
    debt: 0,
    dailyDebtRepayment: 0,
    lifetimeRevenue: 0,
    lifetimeProfit: 0,
    brand: 8,
    reputation: 44,
    marketShare: 1.15,
    researchPoints: 0,
    unlockedTech: ["micro8"],
    unlockedParts: [...STARTER_PART_IDS],
    componentResearch: createStarterResearchLevels(),
    currentResearch: null,
    autoResearch: false,
    employees: {
      production: 6,
      research: 2,
      marketing: 1,
      sales: 2,
      finance: 1,
    },
    departmentLevels: {
      production: 1,
      research: 1,
      marketing: 1,
      sales: 1,
      finance: 1,
    },
    morale: 72,
    factoryLevel: 1,
    warehouseLevel: 1,
    automationLevel: 0,
    factoryCondition: 100,
    maintenanceBudget: 100,
    qualityFocus: 1,
    marketingBudget: 200,
    marketingStrategy: "balanced",
    marketingFocus: "conversion",
    marketingTarget: "all",
    pricingStrategy: "balanced",
    campaign: null,
    autoAcceptContracts: false,
    enterpriseContracts: [],
    productGenerations: { budget: 1, mainstream: 0, performance: 0 },
    products: [
      {
        id: "product-circuit-one",
        blueprintId: "circuit-one",
        name: "Circuit One",
        price: Math.round(starterBuild.buildCost * 1.72),
        launchedDay: 0,
        inventory: 18,
        active: true,
        qualityBonus: 0,
        lastDemand: 0,
        lastProduction: 0,
        lastSales: 0,
        lastContractSales: 0,
        productionTarget: null,
        lastLostSales: 0,
        lastReturns: 0,
        generation: 1,
        configuration: starterConfiguration,
        audience: "office",
        marketSegment: "budget",
      },
    ],
    competitors: createCompetitors(),
    founderShares: 720_000,
    totalShares: 1_000_000,
    sharePrice: 1.85,
    valuation: 1_850_000,
    takeoverRisk: 0,
    takeoverDefenseDays: 0,
    monthlyRevenue: 0,
    monthlyProductRevenue: 0,
    monthlyContractRevenue: 0,
    monthlyExpenses: 0,
    lastMonthRevenue: 0,
    lastMonthProductRevenue: 0,
    lastMonthContractRevenue: 0,
    lastMonthExpenses: 0,
    lastMonthInvestmentIncome: 0,
    lastDayRevenue: 0,
    lastDayProductRevenue: 0,
    lastDayContractRevenue: 0,
    lastDayExpenses: 0,
    history: [
      {
        day: 0,
        revenue: 0,
        productRevenue: 0,
        contractRevenue: 0,
        expenses: 0,
        profit: 0,
        valuation: 1_850_000,
        cash: 175_000,
        debt: 0,
        marketShare: 1.15,
        employees: 12,
        brand: 8,
      },
    ],
    news: [
      {
        id: "welcome",
        day: 0,
        title: "Circuit Forge startet aus einer kleinen Werkhalle",
        body: "Zwölf Menschen, ein einfacher PC und eine große Idee: bessere Technik für alle.",
        category: "company",
        tone: "positive",
      },
      {
        id: "market-open",
        day: 0,
        title: "Heimcomputer werden zum Wachstumsmarkt",
        body: "Analysten erwarten steigende Nachfrage – und einen harten Kampf um Standards.",
        category: "market",
        tone: "neutral",
      },
    ],
    achievements: [],
    selectedSection: "dashboard",
    saveRevision: 0,
    lastSavedAt: now,
    lastTickAt: now,
    onboardingDismissed: false,
  };
}

export const CATEGORY_LABELS: Record<ProductBlueprint["category"], string> = {
  computer: "Computer",
  phone: "Mobile Geräte",
  components: "Komponenten",
  software: "Software & Cloud",
};

export const MARKETING_STRATEGIES = {
  efficient: {
    name: "Effizienz",
    description: "Niedrige Kosten, langsamer Markenaufbau",
    costMultiplier: 0.82,
    demandMultiplier: 0.82,
  },
  balanced: {
    name: "Ausgewogen",
    description: "Gesunde Mischung aus Marke und Absatz",
    costMultiplier: 1,
    demandMultiplier: 1,
  },
  aggressive: {
    name: "Markt erobern",
    description: "Hohe Ausgaben für schnellen Marktanteil",
    costMultiplier: 1.42,
    demandMultiplier: 1.42,
  },
} as const;

export const PRICING_STRATEGIES = {
  value: { name: "Preisführer", demand: 1.2, brand: -0.04 },
  balanced: { name: "Marktpreis", demand: 1, brand: 0 },
  premium: { name: "Premium", demand: 0.76, brand: 0.08 },
} as const;
